### ISSUE TITLE
Memory leak - cPluginLoader

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#100]
https://github.com/Verlihub/verlihub/blob/c0020ff317181d3158aa214c0cac212c4472fa33/src/cpluginmanager.cpp#L99

**Comment by RoLex** [comment]
Вот тут производится удаление: https://github.com/Verlihub/verlihub/blob/master/src/cpluginmanager.cpp#L135

Проблема в том что при остановке хаба не вызывается UnLoadAll, я закомментил этот кусок потому что хаб падает. Сначала надо узнать почему падает, потом вернуть назад UnLoadAll. Какраз сейчас над этим и работаю.

**Comment by pavel-pimenov** [comment]
ок
