### ISSUE TITLE
не работает кик у класса 2

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/verlihub#101]
даю права реганому юзеру класс 2 командой 	!regclass <ник> <класс>, даю ключ классу 2  [::] opkeyclass = 2, разрешаю кик  [::] enablevipkick = 1, и при попытке кика юзером класса 2 выдает в общий чат У вас нет прав на кик пользователя: Penis_Dominator а в личку от бота пишет Пользователь Penis_Dominator с IP-адресом 5.44.169.5.RU 0-го класса был кикнут: <Test2> Нет указанных причин. 
используемая команда +kick Penis_Dominator 
так же классу 10 не приходит используемая команда классом 2. добавлю может играет роль,  [*] unknown_cmd_chat = 1 то есть по идее вообще должна команда пройти в чат.
Информация о хабе:

 [*] Версия: 1.0.4.4
 [*] Локаль: ru_RU.CP1251
 
  .:: Статистика Ledokol:

 Версия скрипта: 2.9.4.57.RU
 Версия Verlihub: 1.0.4.4
 Версия плагина Lua: 1.3.0.6
 Версия библиотек Lua: 5.3.4
 Версия модуля LuaSocket: 3.0-rc1
 Версия MySQL: 10.1.25-MariaDB-1~xenial
 Версия cURL: 7.47.0

**Comment by sirtrifanoff** [comment]
так же при смене профиля с 2 на 1 не исчезает ключ хотя и пишет при перезаходе в мотд Ваш профиль	 1

**Comment by RoLex** [comment]
Исправил обе ошибки, спасибо. Обнови ледо и верли.

**Comment by sirtrifanoff** [comment]
проверил, все работает. тикет можно закрывать.
