### ISSUE TITLE
Удаление регистрации пользователя

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/verlihub#102]
При удалении регистрации класса 3 его ключ и права остаются в силе до перезахода (проверял на команде !cleankicklist - сработала). Я думаю так же и с классами выше, проверял только с 3 классом. Если мне срочно надо удалить регистрацию накосячившего оператора то приходится его еще и кикать пока он неворотил дел.

**Comment by RoLex** [comment]
Ну так кикай, тебе никто не мешает.

**Comment by sirtrifanoff** [comment]
ну так это как бы костыль, обход бага так сказать. Если регистрация удалена то и права все должны быть анулированы.

**Comment by sirtrifanoff** [comment]
Работает, спасибо.
