### ISSUE TITLE
 [::] opkeyclass = 2

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/verlihub#103]
Если установлена переменная  [::] opkeyclass = 2 то после удалении регистрации vip пользователя, ключ не исчезает даже после перезахода, выхода/входа
p.s Вообще вышел, а ник с ключом так и висит. И с ним ничего не сделать, нельзя кикнуть к примеру, висит как фантом.

**Comment by RoLex** [comment]
```
[ 63] Fixed: Operator list appearance after removing user with opkeyclass condition, report by sirtrifanoff
```
