### ISSUE TITLE
TLS encryption

### ISSUE THREAD

**Issue by Shadowghost** [Verlihub/verlihub#106]
Is it possible to configure the hub to use TLS encrypted traffic only? I didn't see anything in the docs explaining how to do it, so if it's possible some additions explaining how to do so would be nice.

**Comment by RoLex** [comment]
The only DC protocol that officially allows using encryption today is ADC, there are clients who support it. Verlihub however is NMDC only, which does not support encryption. Anyone is welcome to contribute to the project though, make it ADC compatible and TLS encrypted after that.

**Comment by Shadowghost** [comment]
Thanks for the Info. Would be nice to write that down as a note, perhaps in the wiki.

**Comment by RoLex** [comment]
This now works with Verlihub 1.2.0.5 + TLS proxy @ https://github.com/Verlihub/tls-proxy
