### ISSUE TITLE
!portinfo

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/verlihub#107]
Вывод вот такой
```
<Талисман> Информация о портах хаба:

 [*] Порт 411: 2809
```
Откуда то нарисовался порт 2809, причем он каждый раз разный рисует
```
<Талисман> Информация о портах хаба:

 [*] Порт 411: 2817
```
Так же в выводе команды portinfo не учитывается extra_listen_ports и avsearservport
```
# netstat -ntulp | grep verlihub
tcp        0      0 185.97.254.40:1411      0.0.0.0:*               LISTEN      1139/verlihub
tcp        0      0 185.97.254.40:4111      0.0.0.0:*               LISTEN      1139/verlihub
tcp        0      0 185.97.254.40:1209      0.0.0.0:*               LISTEN      1139/verlihub
tcp        0      0 185.97.254.40:411       0.0.0.0:*               LISTEN      1139/verlihub
udp        0      0 185.97.254.40:4112      0.0.0.0:*                           1139/verlihub
```

**Comment by RoLex** [comment]
Ахахаха, блеа. Любишь же ты нажравшись в верлик по уши окунуться. Это кол-во юзеров соединившихся через 411 порт. С новым годом! ))

**Comment by sirtrifanoff** [comment]
я не бухаю уже хренову тучу месяцев, включая нг. а работаю в москве по ночам. видать после ночных смен так переклинило, что не увидел? что это не порты, а юзеры ;)
