### ISSUE TITLE
А можно ли сделать компилятор для OpenWRT и LEDE?

### ISSUE THREAD

**Issue by dcbeelinekz** [Verlihub/verlihub#108]
Для установки этого хаба в роутер?

**Comment by RoLex** [comment]
Можно, но с таким большим количеством функционала вряд ли тебе хватит памяти запустить хаб, да и собрать все библиотеки требуемые компилятором - как пример можно взять MySQL сервер.

О какой модели роутера идет речь?

**Comment by dcbeelinekz** [comment]
Вот например у меня **PtokaX 0.5.0.1** стоит как с мая 17 года на роутере mr **3220v2** проц **400**, озу **32** + припаял увеличенную флеш на **8** мб (с али) 
Пашет отлично в локальной сети (20-25 юзеров) но тока никак не пойму почему ники зависают... И мне стало интересно если Верлика поставить так же и протестить но знания по компиляции  низкие как и в программировании. 
Вот если что закинул исходники и готовые пакеты https://github.com/dcbeelinekz/ptokax_lede если интересно

**Comment by RoLex** [comment]
Ты даже не читаешь что я пишу. :)

Поставь на свой роутер MySQL сервер и посмотри сколько ОЗУ он будет кушать. Когда ты увидишь что ему одному не хватает имеющейся памяти, ты поймешь что для самого Верлихаба тем более нет свободной памяти. Проблема в том что ты не имеешь понятия насколько богат функционал Верли, что отражается на используемых хабом и его компонентами системных ресурсов.

**Comment by dcbeelinekz** [comment]
да

**Comment by RoLex** [comment]
Что да? :-D

**Comment by dcbeelinekz** [comment]
иди на хуй , дохуя о себе думаешь Саша !

**Comment by RoLex** [comment]
Бгг, ты оказывается реально даун, как на фотке. Тогда прощаю тебе все твои грехи, живи с миром даун. :)

**Comment by dcbeelinekz** [comment]
э пидарас ибанный!

**Comment by dcbeelinekz** [comment]
ты бы потише сидел. мямлик
