### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by asharma1998** [Verlihub/verlihub#114]
At time of installation by "vh_gui --install"  error came like this
 (0)    2018-11-21 00:53:50 #  main - Configuration directory: /etc/verlihub
 (1)    2018-11-21 00:53:50 #  cMySQL - Connecting to MySQL server verlihub @ localhost / verlihub using charset utf8
 (1)     2018-11-21 00:53:50 #  cMySQL - Connection to MySQL server failed: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
 (0)      2018-11-21 00:53:50 #   main - MySQL connection error

**Comment by RoLex** [comment]
caching_sha2_password is a MySQL plugin, not Verlihub. Please refer to MySQL knowledge base. I assume you only need to install that plugin.
