### ISSUE TITLE
Could NOT find ICU (missing: ICU_LIBRARIES) (found version "60.2.0")

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#115]
sudo apt install libicu-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libicu-dev is already the newest version (60.2-3ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 cmake -DDEFINE_DEBUG=ON -DINSTALL_CMAKE_FILES=OFF ..

    [ OK ] /usr/lib/x86_64-linux-gnu/libicudata.so
    [ OK ] /usr/lib/x86_64-linux-gnu/libicui18n.so
    [ OK ] /usr/lib/x86_64-linux-gnu/libicuuc.so
    [ OK ] /usr/lib/x86_64-linux-gnu/libicuio.so
    [ OK ] _icu_lib_le-NOTFOUND
    [ OK ] /usr/lib/x86_64-linux-gnu/libiculx.so
    [ OK ] _icu_lib_-le-hb-NOTFOUND
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ICU (missing: ICU_LIBRARIES) (found version "60.2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindICU.cmake:166 (find_package_handle_standard_args)
  CMakeLists.txt:128 (Find_Package)

**Comment by RoLex** [comment]
в ubuntu 18.x устанавливается icu версии 60.х, который полностью перешел на стандарт c++11 ( http://site.icu-project.org/download/60#TOC-ICU4C-Platform-Support ), верлик же еще собирается по стандарту c++98. такчто на дынный момент незнаю как решать проблему

**Comment by cyberghost404** [comment]
За это и не люблю 18 убунту)))

**Comment by DooMFeaR** [comment]
Can we get a fix to this?

**Comment by RoLex** [comment]
there is a fix already since Apr 21, 2019.

**Comment by wiejakp** [comment]
> there is a fix already since Apr 21, 2019.

What's the fix? neither ubuntu 18.04 nor 20.04 supports it... 

```
ubuntu@ubuntu:~/Desktop/verlihub-1.2.0.0/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- You can change build options with: -D{OPTION}=ON|OFF
-- You can turn on debug build with: -DDEFINE_DEBUG=ON
-- You can disable all plugins with: -DWITH_PLUGINS=OFF
-- You can also disable specific plugins with: -DWITH_{NAME}=OFF
-- Plugin names: LUA PYTHON PERL FORBID CHATROOM IPLOG ISP MESSENGER STATS REPLACER FLOODPROT
-- If you get errors related to autosprintf, please try with: -DUSE_CUSTOM_AUTOSPRINTF=ON
-- 
-- [ OK ] Library directory: /usr/local/lib
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1") 
-- [ OK ] Found Crypt: /usr/lib/aarch64-linux-gnu/libcrypt.so
-- [ OK ] Found MySQL: /usr/include/mysql, /usr/lib/aarch64-linux-gnu/libmysqlclient.so
-- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.11") 
-- [ OK ] Found MaxMindDB: /usr/include/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu/libmaxminddb.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- [ OK ] Found ICU libraries:
    [ OK ] /usr/lib/aarch64-linux-gnu/libicudata.so
    [ OK ] /usr/lib/aarch64-linux-gnu/libicui18n.so
    [ OK ] /usr/lib/aarch64-linux-gnu/libicuuc.so
    [ OK ] /usr/lib/aarch64-linux-gnu/libicuio.so
    [ OK ] _icu_lib_le-NOTFOUND
    [ OK ] /usr/lib/aarch64-linux-gnu/libiculx.so
    [ OK ] _icu_lib_-le-hb-NOTFOUND
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ICU (missing: ICU_LIBRARIES) (found version "60.2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindICU.cmake:167 (find_package_handle_standard_args)
  CMakeLists.txt:128 (Find_Package)
```

**Comment by RoLex** [comment]
@wiejakp if you read the last post in this thread, right before your post.

**Comment by pvgoran** [comment]
@RoLex But there is no release/tag for 1.2.0.6. The latest one is 1.2.0.0.

**Comment by RoLex** [comment]
thats right. there was no final release since 1.2.0.0 yet. but it dont mean that you cant download latest git version, which is 1.2.0.21

> git clone https://github.com/Verlihub/verlihub.git

**Comment by pvgoran** [comment]
Sure, I can just use the master branch. This is what I ended up with, for now.
