### ISSUE TITLE
cserverdc.cpp - .find("%[CC]")

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#130]
Часто повторяется блок 

tmsg.find("%[CC]") != tmsg.npos
....
Эти циклы часто работают?
Предлагаю оптимизнуть сократить число вызовов .find

![default](https://user-images.githubusercontent.com/920705/49327245-350d3380-f570-11e8-9785-181ac71937cc.png)

**Comment by pavel-pimenov** [comment]
еще вопрос.
функции ReplaceVarInString действительно нужно все вхождения маски менять
или это относится только к одному вхождению?

**Comment by RoLex** [comment]
ты предлагаешь boost заюзать?

по поводу вхождения маски не понял.

у меня есть другой вариант - только первый раз делаем поиск "%[CC]", если в данном тексте есть такое - устанавливаем переменную и сразу делаем замену без поиска, это продолжается до тех пор пока текст не меняется.

**Comment by pavel-pimenov** [comment]
буст тянуть весь не нужно.
можно забрать реализацию.
также нужно сделать поиск стартовый на "%[C" - если такое есть то звать другие реплейсы.
тоже сэкономим.
а ты можешь залогировать такие вызовы на тестовом сервере - чтобы оценить что в эту функцию преедается?
