### ISSUE TITLE
unsigned long cBanList::Ip2Num(const string &ip)

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#134]
cBanList::Ip2Num в 10 раз тормознее sscanf_s

![default](https://user-images.githubusercontent.com/920705/49525793-8fcfc380-f8bf-11e8-9aed-7fc6decb6e25.png)

unsigned long Ip2Num_verli(const string &ip)
{
    int i;
    char c;
    std::istringstream is(ip);
    unsigned long mask = 0;
    is >> i >> c; mask += i & 0xFF; mask <<= 8;
    is >> i >> c; mask += i & 0xFF; mask <<= 8;
    is >> i >> c; mask += i & 0xFF; mask <<= 8;
    is >> i; mask += i & 0xFF;
    return mask;
}

unsigned long Ip2Num_fly(const string &ip)
{
    uint32_t a = 0, b = 0, c = 0, d = 0;
    const int l_Items = sscanf_s(ip.c_str(), "%u.%u.%u.%u", &a, &b, &c, &d);
    if (l_Items == 4)
    {
        return (a << 24) + (b << 16) + (c << 8) + d;
    }
    return 0;
}

int _tmain(int argc, _TCHAR* argv[])
{
    unsigned long sum[2] = {0};
    bool l_bool = false;
    string l_ip = "192.165.3.234";
    const __int64 max_count_verli = 1000000L;
    ticks start = getticks();

    for (__int64 i = 0; i < max_count_verli; ++i)
    {
        sum[0] += Ip2Num_verli(l_ip);
    }
    printf("verlihub_1 = %f\r\n", elapsed(getticks(), start));
    start = getticks();
    for (__int64 i = 0; i < max_count_verli; ++i)
    {
        sum[1] += Ip2Num_fly(l_ip);
    }
    printf("verlihub_2 = %f\r\n", elapsed(getticks(), start));
    printf("sum[0] = %u sump[1] = %u\r\n", sum[0], sum[1]);

**Comment by pavel-pimenov** [comment]
еще заметил что функция зовется 2 раза
Dec  8 14:14:29 oracle verlihub-debug[5144]: [/home/dht/src/verlihub/src/cbanlist.cpp] ip2Num [92.248.251.218]
Dec  8 14:14:29 oracle verlihub-debug[5144]: [/home/dht/src/verlihub/src/cbanlist.cpp] ip2Num [92.248.251.218]

откуда - не знаю
можно тоже оптимизнуть

**Comment by RoLex** [comment]
первый раз - банлист, второй раз - скорее всего геоданные. придумал способ оптимизнуть, щас замучу
