### ISSUE TITLE
SQL - from banlist  where

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#147]
Двойной запрос на бан - если этот для одного юзера, то нужно объединить в один запрос.

![default](https://user-images.githubusercontent.com/920705/49777413-6ffe2c80-fd11-11e8-941a-4890f732e548.png)

1.
Dec 11 06:50:20 oracle verlihub-debug[11820]: [/home/dht/src/verlihub/src/cquery.cpp] Query [select share_size, note_usr, note_op, reason, nick_op, last_hit, date_limit, date_start, range_to, range_fr, host, ban_type, nick, ip from banlist  where ((ip='103.240.160.21') or ( nick = 'viga3') or (nick='_rangeban_' AND 1743822869 BETWEEN range_fr AND range_to ) or (ip='_prefixban_' AND nick=LEFT('viga3',LENGTH(nick)))) and ((`date_limit` >= 1544500220) or (`date_limit` is null) or (`date_limit` = 0)) order by `date_limit` desc limit 1]

2.
Dec 11 06:50:20 oracle verlihub-debug[11820]: [/home/dht/src/verlihub/src/cquery.cpp] Query [select share_size, note_usr, note_op, reason, nick_op, last_hit, date_limit, date_start, range_to, range_fr, host, ban_type, nick, ip from banlist  where ((nick='_shareban_' AND share_size = '72734965940')) and ((`date_limit` >= 1544500220) or (`date_limit` is null) or (`date_limit` = 0)) order by `date_limit` desc limit 1]

![default](https://user-images.githubusercontent.com/920705/49777436-86a48380-fd11-11e8-832f-5927d59def93.png)

**Comment by RoLex** [comment]
это один и тот же юзер да. когда юзер отдает ник хабу - $ValidateNick - хаб проверяет бан на ник, ип, диапазон, префикс. когда юзер отдает myinfo хабу - хаб прпроверяет бан на шару. таким образом мы экономим пару этапов входа юзера - чем больше этапов, тем больше объектов создается. довольно бесполезно если юзера всеравно выкинет за бан по шаре. но чтото надо сделать полюбому

**Comment by pavel-pimenov** [comment]
Думаю будет эффективнее вытащить сразу одним запросом и уже распарсить на клиенте результат

**Comment by RoLex** [comment]
логично, сделаю
