### ISSUE TITLE
PVS-Studio

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#152]
http://oracle.fly-server.ru/pvs-studio/verlihub/

**Comment by RoLex** [comment]
оставшиеся не смог решить. попрошу у тебя помощи )

**Comment by pavel-pimenov** [comment]
Ок. постараюсь сегодня вечером.

**Comment by pavel-pimenov** [comment]
Обновил отчет
http://oracle.fly-server.ru/pvs-studio/verlihub/ - стало меньше )

**Comment by pavel-pimenov** [comment]
обновил отчет http://oracle.fly-server.ru/pvs-studio/verlihub/

**Comment by pavel-pimenov** [comment]
обновил отчет http://oracle.fly-server.ru/pvs-studio/verlihub/
