### ISSUE TITLE
string ip_zone4_min

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#161]
А почему тут не массивы?

string ip_zone_min[3]
string ip_zone_max[3]

https://github.com/Verlihub/verlihub/blob/104ec462dde2abefc7eb780c15fdbba13fe3b6de/src/cdcconf.h#L288-L293

от этого создается лишний код
![default](https://user-images.githubusercontent.com/920705/50538977-ddbbac80-0b89-11e9-9f2e-14dc593aa7f6.png)

**Comment by RoLex** [comment]
потому что это конфиг в виде стрингов которые админ устанавливает через хаб >

!set ip_zone4_min 1.2.3.0
!set ip_zone5_max 1.2.3.255

**Comment by pavel-pimenov** [comment]
ну конфиг это понятно. а зачем он в С++ хранится так-же?

**Comment by pavel-pimenov** [comment]
я тогда закомичу фикс - не закрывай эту issue

**Comment by RoLex** [comment]
лады 👍
