### ISSUE TITLE
verlihub + log-malloc2 = memleak.log

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#165]
https://github.com/samsk/log-malloc2

[verlihub-log-malloc2-memleak.log](https://github.com/Verlihub/verlihub/files/2718013/verlihub-log-malloc2-memleak.log)

**Comment by RoLex** [comment]
интересная штука, вижу новые утечки 👍

**Comment by RoLex** [comment]
можешь обновить? думаю несколько исправил. остались только те что не удаляются при закрытии хаба. т.е утечка никогда не возрастает

**Comment by pavel-pimenov** [comment]
Вот это место не красивое:
https://github.com/Verlihub/verlihub/blob/master/src/chttpconn.cpp#L55

**Comment by RoLex** [comment]
я так и думал что большинство утечек - ложные. что эта программа, что valgrind, не в состоянии уследить до самого последнего момента разрушения программы и их объектов. так что все открытые файлы, mysql, dl_open, icu и т.д - являются ложными. вот пример для мускула > https://bugs.mysql.com/bug.php?id=7619 - mysql_init() и mysql_close() это единственный и правильный способ работы с библиотекой мускула через внешние приложения

**Comment by pavel-pimenov** [comment]
Может у меня в centOS mysql либа с утечкой. вот она и детектится

**Comment by RoLex** [comment]
у меня тоже самое, и у других пользователей тоже. тоже самое с icu - все закрывается корректно, но либа освобождает ресурсы позже

**Comment by pavel-pimenov** [comment]
Попробовал птоху запустить - она почему-то строки не показывает где идет выделение памяти

отключил оптимизацию не помогло

CXXFLAGS = -std=c++11 -g -Wall -Wextra -D_WITH_SQLITE -DFLYLINKDC_USE_DB -DxUSE_FLYLINKDC_EXT_JSON
CCFLAGS = -g -Wall -Wextra

к верли какие флаги идут для C++?


![default](https://user-images.githubusercontent.com/920705/50846883-47556b00-1381-11e9-9d9e-27edb86abba5.png)

**Comment by RoLex** [comment]
стандартные, а точнее не указано ничего кроме:

всегда:

`SET(CMAKE_CXX_STANDARD 98)`

в дебаг режиме:

`IF(DEFINE_DEBUG)
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -O3 -g")`
