### ISSUE TITLE
CentOS docker build error perl

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#171]
#Dockerfile:
FROM centos:latest
MAINTAINER pavel.pimenov@gmail.com
RUN yum install -y deltarpm epel-release
RUN yum install -y gcc-c++ cmake git zlib libmaxminddb libmaxminddb-devel libicu-devel mysql-server mysql mysql-devel openssl openssl-devel gettext gettext-devel pcre pcre-devel python-devel perl-devel lua-devel
RUN git clone --depth 1 https://github.com/Verlihub/verlihub
WORKDIR /verlihub
RUN mkdir build
WORKDIR /verlihub/build
RUN cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
RUN make

.....

docker build -t flylinkdc/verlihub-centos .

[ 58%] Building CXX object plugins/python/CMakeFiles/libvh_python_wrapper.dir/wrapper.cpp.o
Linking CXX shared module libvh_python_wrapper.so
[ 58%] Built target libvh_python_wrapper
Scanning dependencies of target libperl_pi
[ 58%] Building CXX object plugins/perl/CMakeFiles/libperl_pi.dir/callbacks.cpp.o
Can't locate ExtUtils/Embed.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
In file included from /verlihub/plugins/perl/cperlmulti.h:24:0,
                 from /verlihub/plugins/perl/cpiperl.h:27,
                 from /verlihub/plugins/perl/callbacks.cpp:25:
/verlihub/plugins/perl/cperlinterpreter.h:34:71: fatal error: EXTERN.h: No such file or directory
 #include <EXTERN.h>               /* from the Perl distribution     */
                                                                       ^
compilation terminated.
make[2]: *** [plugins/perl/CMakeFiles/libperl_pi.dir/callbacks.cpp.o] Error 1
make[1]: *** [plugins/perl/CMakeFiles/libperl_pi.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2

**Comment by pavel-pimenov** [comment]
Fix : yum install perl-ExtUtils-Embed

**Comment by RoLex** [comment]
https://github.com/Verlihub/verlihub/wiki/Installation#centos
