### ISSUE TITLE
Error when trying to ping your verlihub hub

### ISSUE THREAD

**Issue by Kcchouette** [Verlihub/verlihub#174]
Hello

When trying to ping your official dchub://hub.verlihub.net:7777, I have the following message:

```
 From now on users that don't have valid Verlihub address in their description will no longer be able to access and use this hub.
 Please put in your description the address of your or your friends Verlihub, if you have class 3 or above there, and reconnect.
 If you don't run Verlihub yet, you can temporarily put address of this hub in your description: dchub://hub.verlihub.net:7777/
 Any other guests are not welcome here and will be redirected to another public hub, we are really sorry for the inconvenience.
[...]
 Best regards from VAZ.
```

Can you disable this check?
Or is it a check to try to forbid pinger?

**Comment by RoLex** [comment]
this hub is for verlihub administrators only. but sure, pingers are allowed if they dont visit too often. what is the nick of your pinger?

**Comment by Kcchouette** [comment]
> verlihub administrators only

Maybe you should in this case delete it on public hublist (example, here cache of http://www.te-home.net/?do=hublist&get=hublist.xml: https://dpaste.de/cxnr/raw; your hub is listed)

> what is the nick of your pinger

Sadly my pinger has no-fixed nick.

**Comment by RoLex** [comment]
i would like to keep all my hubs on my hublist ;-)

why dont you make a fixed nick for this particular hub? then problem is solved. another solution is to give your pinger a description as it says in block message when you try to login, for this specific hub

if you dont have this functionality in your hublist, i can help you to create it

**Comment by Kcchouette** [comment]
> why dont you make a fixed nick for this particular hub?

It's not a function I want to have. Some is banning client they don't have fixed description, mine is to be considered as a no-fixed nick pinger.

> another solution is to give your pinger a description as it says in block message when you try to login

My pinger is a general pinger, it takes the url of a hub and simply ping it using not-fixed value. So the only value I'm giving to my pinger is the URL of a hub.
Even if I'm **really** against doing a particular thing for each particular hub, I can always give you the source of my pinger as it is open source: https://github.com/direct-connect/go-dcpp/tree/master/cmd/dcping

But like I previously said, it's sad to show a hub as public when it's reserved to only a few part of people, here verlihub administrator only

**Comment by RoLex** [comment]
why is it sad? lol

thats how i want it to be. im trying to give you few solutions, but you dont like them. so we have a deal - i dont accept your piger, you dont show my hub. i think is great deal =)

**Comment by Kcchouette** [comment]
> why is it sad? lol

It's sad to say "yeah it's public, but only for verlihub, and only for admin"

The problem here is not my pinger, the problem is your hub which is listed on a public hublist as **public** but it's **not at all** public (but reserved to verlihub admin)

**Comment by RoLex** [comment]
it is public, for any verlihub admin, or any verlihub op, or any verlihub admin who would like to begin using verlihub
