### ISSUE TITLE
Invalid MySQL syntax during post-install database creation

### ISSUE THREAD

**Issue by rfilmyer** [Verlihub/verlihub#180]
When running `vh --install`, I ran into an issue when creating the database. After some bug hunting, I found it was because of this line:

https://github.com/Verlihub/verlihub/blob/5ec7c61b0c1561d4692741e76c60bab8b97df246/scripts/vh.in#L821

The final command in that call, `GRANT ALL ON db to user@ip identified by 'password'`, throws a syntax error on MySQL 8. `IDENTIFIED BY` is not a part of the `GRANT` command. If you remove it it works (eg `GRANT ALL ON verlihub TO verlihub@verlihub` executes fine, and `IDENTIFIED BY` isn't necessary because you created the user a few lines ago).

**Comment by RoLex** [comment]
alright. so workaround for this would be detection of mysql version and execution of different queries depending on version?

**Comment by rfilmyer** [comment]
Since the role is created before that step (presumably with a password), is
the IDENTIFIED BY necessary in earlier MySQL versions?

**Comment by rfilmyer** [comment]
I notice that adding a user seems to fail (since mysql errors get thrown to /dev/null I can't tell what the syntax error might be). What's the latest MySQL version that you guys have been able to get working with this without any problems? 

It may be easier for me to get my server running on that, rather than try to get things working with a newer version, short-term.

**Comment by RoLex** [comment]
`vh -u` adds user to registered users list in your hub. its unrelated to mysql users.
