### ISSUE TITLE
error when running cmake.. on Centos 7

### ISSUE THREAD

**Issue by uzzitm** [Verlihub/verlihub#183]
error when running cmake ..

[root@server build]# make
make[2]: *** No rule to make target `/usr/lib64/libmysqlclient.so', needed by `src/libverlihub.so'.  Stop.
make[1]: *** [src/CMakeFiles/libverlihub.dir/all] Error 2
make: *** [all] Error 2

any help please?

**Comment by RoLex** [comment]
you show only log after writing make, but you say that you get error during cmake. please post cmake log.

**Comment by RoLex** [comment]
when you execute command in terminal, you get back log from command. i need to see the complete cmake log.

**Comment by uzzitm** [comment]
cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
--
-- You can change build options with: -D{OPTION}=ON|OFF
-- You can turn on debug build with: -DDEFINE_DEBUG=ON
-- You can disable all plugins with: -DWITH_PLUGINS=OFF
-- You can also disable specific plugins with: -DWITH_{NAME}=OFF
-- Plugin names: LUA PYTHON PERL FORBID CHATROOM IPLOG ISP MESSENGER STATS REPLACER FLOODPROT
-- If you get errors related to autosprintf, please try with: -DUSE_CUSTOM_AUTOSPRINTF=ON
--
-- [ OK ] Library directory: /usr/local/lib
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k")
-- [ OK ] Found Crypt: /usr/lib64/libcrypt.so
-- [ OK ] Found MySQL: /usr/include/mysql, /usr/lib64/libmysqlclient.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- [ OK ] Found MaxMindDB: /usr/include, /usr/lib64/libmaxminddb.so
-- [ OK ] Found ICU libraries:
    [ OK ] /usr/lib64/libicudata.so
    [ OK ] /usr/lib64/libicui18n.so
    [ OK ] /usr/lib64/libicuuc.so
    [ OK ] /usr/lib64/libicuio.so
-- Found ICU: /usr/lib64/libicudata.so;/usr/lib64/libicui18n.so;/usr/lib64/libicuuc.so;/usr/lib64/libicuio.so (found version "50.2.0")
-- [ OK ] Found DL: /usr/include, /usr/lib64/libdl.so
-- [ OK ] Found PCRE: /usr/include, /usr/lib64/libpcre.so;/usr/lib64/libpcreposix.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1")
-- Looking for gettext
-- Looking for gettext - found
-- [ OK ] Found GetText: /usr/include
-- Looking for dgettext
-- Looking for dgettext - found
-- Found Libintl: /usr/include
-- [ OK ] Found asprintf library: /usr/lib64/libasprintf.so
-- Looking for include file errno.h
-- Looking for include file errno.h - found
-- Looking for include file sys/poll.h
-- Looking for include file sys/poll.h - found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- [ OK ] Build type: Release
-- [ OK ] Generating configuration file: /root/verlihub-1.3.0.0/src/config.h
-- [ OK ] Generating directory settings file: /root/verlihub-1.3.0.0/src/dirsettings.h
-- [ OK ] Generating configuration file: /root/verlihub-1.3.0.0/src/verlihub_config
-- [ OK ] Building plugman plugin.
-- Found Lua52: /usr/lib64/liblua.so;/usr/lib64/libm.so (found version "5.1.4")
-- [ OK ] Building lua plugin.
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7")
-- [ OK ] Building python plugin.
-- Found Perl: /usr/bin/perl (found version "5.16.3")
-- Found PerlLibs: /usr/lib64/perl5/CORE/libperl.so (found version "5.16.3")
-- [ OK ] Building perl plugin.
-- [ OK ] Building forbid plugin.
-- [ OK ] Building chatroom plugin.
-- [ OK ] Building iplog plugin.
-- [ OK ] Building isp plugin.
-- [ OK ] Building messenger plugin.
-- [ OK ] Building stats plugin.
-- [ OK ] Building replacer plugin.
-- [ OK ] Building floodprot plugin.
-- Generating vh_daemon
-- Generating vh_lib
-- Generating vh_gui
-- Generating vh
-- Generating vhm
-- Generating vh_regimporter
-- Generating vh_migration_0.9.8eto1.0
-- Generating vh_run_integration_test
--
-- ========== Build information ==========
--
-- [ OK ] Hub version: 1.3.0.0
-- [ OK ] CMAKE_INSTALL_PREFIX: /usr/local
-- [ OK ] Building plugins: 12 of 12
-- [ OK ] Now please run "make" as current user and "make install" as super user.
--
-- ================= End =================
--
-- Configuring done
-- Generating done
-- Build files have been written to: /root/verlihub-1.3.0.0/src
[root@server src]# make
Scanning dependencies of target libverlihub
[  0%] Building CXX object src/CMakeFiles/libverlihub.dir/casyncconn.cpp.o
[  1%] Building CXX object src/CMakeFiles/libverlihub.dir/casyncsocketserver.cpp.o
[  2%] Building CXX object src/CMakeFiles/libverlihub.dir/cban.cpp.o
[  2%] Building CXX object src/CMakeFiles/libverlihub.dir/cbanlist.cpp.o
[  3%] Building CXX object src/CMakeFiles/libverlihub.dir/ccallbacklist.cpp.o
[  4%] Building CXX object src/CMakeFiles/libverlihub.dir/cchatconsole.cpp.o
[  4%] Building CXX object src/CMakeFiles/libverlihub.dir/ccommand.cpp.o
[  5%] Building CXX object src/CMakeFiles/libverlihub.dir/ccommandcollection.cpp.o
[  6%] Building CXX object src/CMakeFiles/libverlihub.dir/cconfigbase.cpp.o
[  6%] Building CXX object src/CMakeFiles/libverlihub.dir/cconfigfile.cpp.o
[  7%] Building CXX object src/CMakeFiles/libverlihub.dir/cconfigitembase.cpp.o
[  8%] Building CXX object src/CMakeFiles/libverlihub.dir/cconfmysql.cpp.o
[  8%] Building CXX object src/CMakeFiles/libverlihub.dir/cconnchoose.cpp.o
[  9%] Building CXX object src/CMakeFiles/libverlihub.dir/cconndc.cpp.o
[ 10%] Building CXX object src/CMakeFiles/libverlihub.dir/cconnpoll.cpp.o
[ 10%] Building CXX object src/CMakeFiles/libverlihub.dir/cconnselect.cpp.o
[ 11%] Building CXX object src/CMakeFiles/libverlihub.dir/cconntypes.cpp.o
[ 12%] Building CXX object src/CMakeFiles/libverlihub.dir/ccustomredirect.cpp.o
[ 12%] Building CXX object src/CMakeFiles/libverlihub.dir/ccustomredirects.cpp.o
[ 13%] Building CXX object src/CMakeFiles/libverlihub.dir/cdbconf.cpp.o
[ 14%] Building CXX object src/CMakeFiles/libverlihub.dir/cdcclient.cpp.o
[ 14%] Building CXX object src/CMakeFiles/libverlihub.dir/cdcclients.cpp.o
[ 15%] Building CXX object src/CMakeFiles/libverlihub.dir/cdccommand.cpp.o
[ 16%] Building CXX object src/CMakeFiles/libverlihub.dir/cdcconf.cpp.o
[ 16%] Building CXX object src/CMakeFiles/libverlihub.dir/cdcconsole.cpp.o
[ 17%] Building CXX object src/CMakeFiles/libverlihub.dir/cdcproto.cpp.o
[ 18%] Building CXX object src/CMakeFiles/libverlihub.dir/cdctag.cpp.o
[ 18%] Building CXX object src/CMakeFiles/libverlihub.dir/cfreqlimiter.cpp.o
[ 19%] Building CXX object src/CMakeFiles/libverlihub.dir/chttpconn.cpp.o
[ 20%] Building CXX object src/CMakeFiles/libverlihub.dir/cmaxminddb.cpp.o
[ 20%] Building CXX object src/CMakeFiles/libverlihub.dir/cinfoserver.cpp.o
[ 21%] Building CXX object src/CMakeFiles/libverlihub.dir/cinterpolexp.cpp.o
[ 22%] Building CXX object src/CMakeFiles/libverlihub.dir/ckick.cpp.o
[ 22%] Building CXX object src/CMakeFiles/libverlihub.dir/ckicklist.cpp.o
[ 23%] Building CXX object src/CMakeFiles/libverlihub.dir/clog.cpp.o
[ 24%] Building CXX object src/CMakeFiles/libverlihub.dir/cmeanfrequency.cpp.o
[ 24%] Building CXX object src/CMakeFiles/libverlihub.dir/cmessagedc.cpp.o
[ 25%] Building CXX object src/CMakeFiles/libverlihub.dir/cmutex.cpp.o
[ 26%] Building CXX object src/CMakeFiles/libverlihub.dir/cmysql.cpp.o
[ 27%] Building CXX object src/CMakeFiles/libverlihub.dir/cobj.cpp.o
[ 27%] Building CXX object src/CMakeFiles/libverlihub.dir/cpcre.cpp.o
[ 28%] Building CXX object src/CMakeFiles/libverlihub.dir/cpenaltylist.cpp.o
[ 29%] Building CXX object src/CMakeFiles/libverlihub.dir/cpluginbase.cpp.o
[ 29%] Building CXX object src/CMakeFiles/libverlihub.dir/cpluginloader.cpp.o
[ 30%] Building CXX object src/CMakeFiles/libverlihub.dir/cpluginmanager.cpp.o
[ 31%] Building CXX object src/CMakeFiles/libverlihub.dir/cprotocol.cpp.o
[ 31%] Building CXX object src/CMakeFiles/libverlihub.dir/cprotocommand.cpp.o
[ 32%] Building CXX object src/CMakeFiles/libverlihub.dir/cquery.cpp.o
[ 33%] Building CXX object src/CMakeFiles/libverlihub.dir/creglist.cpp.o
[ 33%] Building CXX object src/CMakeFiles/libverlihub.dir/creguserinfo.cpp.o
[ 34%] Building CXX object src/CMakeFiles/libverlihub.dir/cserverdc.cpp.o
[ 35%] Building CXX object src/CMakeFiles/libverlihub.dir/csetuplist.cpp.o
[ 35%] Building CXX object src/CMakeFiles/libverlihub.dir/ctempfunctionbase.cpp.o
[ 36%] Building CXX object src/CMakeFiles/libverlihub.dir/cthread.cpp.o
[ 37%] Building CXX object src/CMakeFiles/libverlihub.dir/cthreadwork.cpp.o
[ 37%] Building CXX object src/CMakeFiles/libverlihub.dir/ctime.cpp.o
[ 38%] Building CXX object src/CMakeFiles/libverlihub.dir/ctimeout.cpp.o
[ 39%] Building CXX object src/CMakeFiles/libverlihub.dir/ctrigger.cpp.o
[ 39%] Building CXX object src/CMakeFiles/libverlihub.dir/ctriggers.cpp.o
[ 40%] Building CXX object src/CMakeFiles/libverlihub.dir/cuser.cpp.o
[ 41%] Building CXX object src/CMakeFiles/libverlihub.dir/cusercollection.cpp.o
[ 41%] Building CXX object src/CMakeFiles/libverlihub.dir/cvhplugin.cpp.o
[ 42%] Building CXX object src/CMakeFiles/libverlihub.dir/cvhpluginmgr.cpp.o
[ 43%] Building CXX object src/CMakeFiles/libverlihub.dir/cworkerthread.cpp.o
[ 43%] Building CXX object src/CMakeFiles/libverlihub.dir/czlib.cpp.o
[ 44%] Building CXX object src/CMakeFiles/libverlihub.dir/i18n.cpp.o
[ 45%] Building CXX object src/CMakeFiles/libverlihub.dir/script_api.cpp.o
[ 45%] Building CXX object src/CMakeFiles/libverlihub.dir/stdafx.cpp.o
[ 46%] Building CXX object src/CMakeFiles/libverlihub.dir/stringutils.cpp.o
[ 47%] Building CXX object src/CMakeFiles/libverlihub.dir/thasharray.cpp.o
[ 47%] Building CXX object src/CMakeFiles/libverlihub.dir/tpluginbase.cpp.o
make[2]: *** No rule to make target `/usr/lib64/libmysqlclient.so', needed by `src/libverlihub.so'.  Stop.
make[1]: *** [src/CMakeFiles/libverlihub.dir/all] Error 2
make: *** [all] Error 2

**Comment by uzzitm** [comment]
mariadb-devel is already installed together with mariadb following this tutorial

https://mariadb.com/resources/blog/installing-mariadb-10-on-centos-7-rhel-7/

yum install mariadb-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.hostico.ro
 * epel: fedora.mirrors.telekom.ro
 * extras: mirrors.m247.ro
 * updates: mirrors.m247.ro
Package 1:mariadb-devel-5.5.68-1.el7.x86_64 is obsoleted by MariaDB-devel-10.5.9-1.el7.centos.x86_64 which i                  s already installed

**Comment by uzzitm** [comment]
whereis libmysqlclient.so
libmysqlclient: /usr/lib64/libmysqlclient.a /usr/lib64/libmysqlclient.so

in winscp link looks broken, dont know why

![libmysql](https://user-images.githubusercontent.com/16853669/113047378-e60c5300-91a9-11eb-882a-ded920e0d8f6.PNG)

**Comment by uzzitm** [comment]
fixed by uninstalling MariaDB 10.5.9 and installing MariaDB 5.5.68

**Comment by RoLex** [comment]
@uzzitm 

oh shit. why so huge version difference?

**Comment by uzzitm** [comment]
As i looks latest centos 7 comes default with 5.x but the lastest mariadb is 10x so thats why i installed it
