### ISSUE TITLE
#include <sys/vtimes.h>  No such file or directory :)

### ISSUE THREAD

**Issue by 1o1o1** [Verlihub/verlihub#185]
last archlinux kernel linux-5.11.13.arch
error :)

[ 19%] Building CXX object src/CMakeFiles/libverlihub.dir/cinfoserver.cpp.o
/srv/apps/verlihub/src/verlihub-1.3.0.0/src/cinfoserver.cpp:34:11: фатальная ошибка: sys/vtimes.h: Нет такого файла или каталога
   34 |  #include <sys/vtimes.h>
      |           ^~~~~~~~~~~~~~
компиляция прервана.
make[2]: *** [src/CMakeFiles/libverlihub.dir/build.make:496: src/CMakeFiles/libverlihub.dir/cinfoserver.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:508: src/CMakeFiles/libverlihub.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2
==> ОШИБКА: Произошел сбой в build().
    Прерывание...

**Comment by RoLex** [comment]
try to command that line >

**Comment by 1o1o1** [comment]
It's Ok) compiling well 

But not workin with new lua-5.4.3 :(
work well with lua-5.4.2 ...

**Comment by RoLex** [comment]
i know. im currently testing lua 5.4.3, will fix soon

**Comment by 1o1o1** [comment]
strange!  On boards with cpu arm64 aarch64  compiling well !!! no error

[ 18%] Building CXX object src/CMakeFiles/libverlihub.dir/cmaxminddb.cpp.o
[ 19%] Building CXX object src/CMakeFiles/libverlihub.dir/cinfoserver.cpp.o  <---- :)
[ 19%] Building CXX object src/CMakeFiles/libverlihub.dir/cinterpolexp.cpp.o
[ 20%] Building CXX object src/CMakeFiles/libverlihub.dir/ckick.cpp.o

**Comment by RoLex** [comment]
what is not working?

**Comment by 1o1o1** [comment]
with icu 69 compiling But not working

мая 15 11:23:11 dchub.in.ua systemd[1]: Started Process Core Dump (PID 513449/UID 0).
мая 15 11:23:12 dchub.in.ua systemd-coredump[513450]: Process 513428 (verlihub) of user 0 dumped core.
                                                         
                                                         Stack trace of thread 513428:
                                                         #0  0x00007faa6fa61ef5 raise (libc.so.6 + 0x3cef5)
                                                         #1  0x00007faa6fa4b862 abort (libc.so.6 + 0x26862)
                                                         #2  0x00007faa6fe7f4ab _ZN9nVerliHub7nSocket9cConnPoll6OptOutEiNS_6nEnums8tChEventE (libverlihub.so + 0x964ab)
                                                         #3  0x00007faa6fe5a3bc _ZN9nVerliHub7nSocket10cAsyncConn8CloseNowEv (libverlihub.so + 0x713bc)
                                                         #4  0x00007faa6fe5a751 _ZN9nVerliHub7nSocket10cAsyncConnC2EiPNS0_18cAsyncSocketServerENS_6nEnums9tConnTypeE (libverlihub.so + 0x71751)
                                                         #5  0x00007faa6fe5d0fc _ZN9nVerliHub7nSocket18cAsyncSocketServer14StartListeningEi (libverlihub.so + 0x740fc)
                                                         #6  0x00007faa6ff288fe _ZN9nVerliHub7nSocket9cServerDC14StartListeningEi (libverlihub.so + 0x13f8fe)
                                                         #7  0x000055fddf5316e7 main (verlihub + 0x26e7)
                                                         #8  0x00007faa6fa4cb25 __libc_start_main (libc.so.6 + 0x27b25)
                                                         #9  0x000055fddf53190e _start (verlihub + 0x290e)
мая 15 11:23:12 dchub.in.ua kernel: audit: type=1131 audit(1621066992.549:49218): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3694-513449-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
мая 15 11:23:12 dchub.in.ua audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3694-513449-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
мая 15 11:23:12 dchub.in.ua mariadbd[508257]: 2021-05-15 11:23:12 7 [Warning] Aborted connection 7 to db: 'verlihub' user: 'verlihub' host: 'localhost' (Got an error reading communication packets)
мая 15 11:23:12 dchub.in.ua systemd[1]: systemd-coredump@3694-513449-0.service: Deactivated successfully.

**Comment by 1o1o1** [comment]
in err.old:
/usr/bin/vh_daemon: строка 35: 513768 Аварийный останов         (стек памяти сброшен на диск) $VERLIHUB $*
