### ISSUE TITLE
Fix for low ports root please add to wiki

### ISSUE THREAD

**Issue by kiam001** [Verlihub/verlihub#189]
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/verlihub

**Comment by RoLex** [comment]
@kiam001
Could you please explain more about this? You just said something I have absolutely no idea about. If you would like to contribute, please explain what this is, how it works, and what we and you need this for.

**Comment by kiam001** [comment]
Hi @RoLex it will allow verlihub to run it with lower ports as 1024 as sample 411 without run it with root acess

**Comment by kiam001** [comment]
Here more Information https://gist.github.com/chairco/99342c9e5d7fba51e1b8f69a7b5ccf11

**Comment by wiejakp** [comment]
@kiam001 , this is not verlihub limitation -- it's linux limitation. There are various way to go around it, one way is to disable the security check on your system or forward external port 411 into your internal port (that is higher than port 1024) like 4111 by using iptables, for example:

`-A PREROUTING -p tcp -m tcp -i eth0 --dport 411 -j REDIRECT  --to-port 4111`
