### ISSUE TITLE
memset(mProtoFloodTimes, 0, sizeof(mProtoFloodTimes));

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#197]
[build] /home/ppa/src/verlihub/src/cconndc.cpp:53:15: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class nVerliHub::nUtils::cTime’; use assignment or value-initialization instead [-Wclass-memaccess]
[build]    53 |         memset(mProtoFloodTimes, 0, sizeof(mProtoFloodTimes));
[build]       |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[build] /home/ppa/src/verlihub/src/cconndc.cpp:54:15: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class nVerliHub::nUtils::cTime’; use assignment or value-initialization instead [-Wclass-memaccess]
[build]    54 |         memset(mProtoFloodReports, 0, sizeof(mProtoFloodReports));
[build]       |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by RoLex** [comment]
я это исправил уже. ты стабильный релиз 1.4.0.0 смотришь походу. запили последний код лучше > https://github.com/Verlihub/verlihub.git

**Comment by pavel-pimenov** [comment]
смотрю master https://github.com/Verlihub/verlihub/blob/15e73b122732110c16bf316ce71be9407222ee70/src/cconndc.cpp#L53

**Comment by RoLex** [comment]
аа, сорян, ты прав. я исправил тоже самое в cserverdc.cpp, тут не доглядел. спасибо

**Comment by pavel-pimenov** [comment]
нужно убрать memset вообще - нельзя так зачищать объекты которые классы.
можно получить побочный эффект - инициализацию в таких случаях делает конструктор
https://stackoverflow.com/questions/66368061/error-clearing-an-object-of-non-trivial-type-with-memset

**Comment by RoLex** [comment]
если мне не изменяет память, без memset тоже выдает ошибку или предупреждение. что тогда делать?

**Comment by pavel-pimenov** [comment]
Просто нужно убрать из конструктора - но проверь под отладкой что находится в массивах.
  memset(mProtoFloodTimes, 0, sizeof(mProtoFloodTimes));
  memset(mProtoFloodReports, 0, sizeof(mProtoFloodReports));

у тебя массивы в классе объявлены как

cTime mProtoFloodTimes[nEnums::ePF_LAST];
cTime mProtoFloodReports[nEnums::ePF_LAST];

т.е. при создании объекта cConnDC сработает конструктор для каждого элемента этого элемента
и отработает вот такой код
	cTime(){Get();}
	cTime & Get(){gettimeofday(this,NULL);return *this;}

но потом ты его затираешь на 0x00 - не знаю зачем так делается.
может быть конструктор cTime(){Get();} доложен быть другой?
и прописывать базовый timeval в 0x00 ?

/* A time value that is accurate to the nearest
   microsecond but also has a range of years.  */
struct timeval
{
#ifdef __USE_TIME_BITS64
  __time64_t tv_sec;		/* Seconds.  */
  __suseconds64_t tv_usec;	/* Microseconds.  */
#else
  __time_t tv_sec;		/* Seconds.  */
  __suseconds_t tv_usec;	/* Microseconds.  */
#endif
};

**Comment by RoLex** [comment]
ты прав, чтото я попутал. все работает
