### ISSUE TITLE
int cConnDC::Send(string &data, bool AddPipe, bool Flush)

### ISSUE THREAD

**Issue by pavel-pimenov** [Verlihub/verlihub#199]
Почему-то возникают вызовы с пустотой - это баг?
временно добавил лог:
int cConnDC::Send(string &data, bool AddPipe, bool Flush)
{
	if(data.empty() && AddPipe == false)
	{
		LogStream() << "data.empty() && AddPipe == false" << endl;	
	}
![изображение](https://user-images.githubusercontent.com/920705/223653264-ae63f4c5-4d42-4eac-ba8c-76f8cdb87647.png)

**Comment by RoLex** [comment]
ты забыл bool Flush - он должен быть true поскольку это функция FlushCache() зовется. по таймеру отдается залежавшийся буфер, который не был отдан ранее и не имеет приоритета. есть два типа буфера - первый который надо отдать сейчас, поскольку он хранит инфу о заходе/выходе юзеров - должно происходить в реальном времени чтоб не получить рассинхрон и не висели мертвые юзеры на хабе - у тебя было такое на птохе помню. а второй буфер - это чат, поиск и прочая ебулда у которой нет приоритета - этот вид отдается по таймеру всем сразу.

поскольку ты один на тестовом хабе, то у тебя нет 50 поисковых запросов каждую секунду например, и соответственно отправлять нечего. если посмотришь дальше по цепочке cConnDC::Send > cAsyncConn::Write - там есть проверки на наличие первого и второго буфера.

**Comment by pavel-pimenov** [comment]
Понятно. а у тебя если программа, эмулирующая реальную нагрузку на хаб?

**Comment by pavel-pimenov** [comment]
у меня хаб пока в virtualbox на локальном компе.
подниму в интернте - напишу.)
