### ISSUE TITLE
CMAKE_INSTALL_PREFIX is not respected durin installation step

### ISSUE THREAD

**Issue by Kicer86** [Verlihub/verlihub#208]
I have set CMAKE_INSTALL_PREFIX cmake variable during configuration step to a subdir in my home dir, but installation step tries to write to /usr

**Comment by Kicer86** [comment]
It is caused by ```OPTION(INSTALL_CMAKE_FILES "Install the *.cmake files into the CMake root" ON)```
Maybe it should be OFF by default if CMAKE_INSTALL_PREFIX is not within CMAKE_ROOT?

**Comment by RoLex** [comment]
You can override any CMake option in command line like this:

``-DCMAKE_INSTALL_PREFIX=/home/user/dir``

And you can specify multiple options if not only this one is a problem for you.

**Comment by Kicer86** [comment]
Yes, that's right. What was a bit confusing for me was that I actually chose `-DCMAKE_INSTALL_PREFIX=/home/user/dir` and then I got an installation error at 'install' step because `/usr/lib/cmake` was about to be updated with `Find` script for verlihub. 

Turning `INSTALL_CMAKE_FILES` off fixed the problem but I needed to read `CMakeLists.txt` files first to understand what's going on there.

**Comment by RoLex** [comment]
Did you solve your issue?

**Comment by Kicer86** [comment]
I did, I'm just pointing possible confusions from the user perspective
