### ISSUE TITLE
'Command List' and 'Variable List' on wiki are broken

### ISSUE THREAD

**Issue by Kicer86** [Verlihub/verlihub#212]
After clicking on 'Command List' or 'Variable List' on 'https://github.com/Verlihub/verlihub/wiki/' I am being redirected to main page with the message 'You do not have permission to update this wiki.'

**Comment by RoLex** [comment]
@wiejakp will help you when he has time.

**Comment by RoLex** [comment]
In fact I was too fast, sorry @wiejakp. There is nothing wrong with the menu links. They work as they should. Logged in or not.

@Kicer86 clear your cookies.

**Comment by Kicer86** [comment]
@RoLex I've opened wiki from a browser which I never used to access this wiki. The message is no more, but I'm still immediately redirected to the main wiki page

**Comment by RoLex** [comment]
@ https://httpstatus.io/

````
  | Request URL | Status codes | Redirects
  | https://github.com/Verlihub/verlihub/wiki/Command-List | 200 | 0
  | https://github.com/Verlihub/verlihub/wiki/Variable-List | 200 | 0
````

**Comment by Kicer86** [comment]
https://github.com/user-attachments/assets/35a8945d-9bb9-48fe-9310-26c07207faf5

Here is recording from my phone (another browser never used to access this wiki), where I'm clicking last 3 links in manual section (variable list, command list, plugins)

**Comment by Kicer86** [comment]
Apparently it video doesn't work well on github, so yt upload: https://www.youtube.com/shorts/LQNxGvVnt4M

**Comment by RoLex** [comment]
I thought you were talking about the menu on the right. Yes, the footnote menu was leading to unexisting pages, fixed, thanks. There are many errors in Wiki, we are working on it when we have time.
