### ISSUE TITLE
Building documentation needs correction

### ISSUE THREAD

**Issue by mikekmv** [Verlihub/verlihub#7]
Tested on OpenBSD
Should add to INSTALL file:
```
Prerequisites:
    bash
```
Without "optional" GeoIP won't compile too,
may be, w/o other optional packages will not compile too.

**Comment by mikekmv** [comment]
Why cmake says:
```
+ lua (>=5.2): Allows you to use scripts written in Lua (http://www.lua.org) <http://www.lua.org> (WITH_LUA)
+ python (>=2.7): Allows you to use scripts written with Python (http://www.python.org) <http://www.python.org> (WITH_PYTHON)
``` 
But http://www.verlihub.net/doc/page/manual.installation and https://github.com/Verlihub/verlihub/blob/master/CMakeLists.txt#L218-L219 says different ?

**Comment by mikekmv** [comment]
To install Verlihub on Centos dependences use:
```
yum install openssl-devel gettext-devel pcre-devel mysql-devel python-devel perl-devel lua-devel
```
etc

**Comment by mikekmv** [comment]
for CentOS-6.7
```
sudo yum install perl-core
```
is mandatory for perl plugin.

**Comment by mikekmv** [comment]
For BSD systems should be added libexecinfo dependency.

**Comment by mikekmv** [comment]
On BSD and Darwin (MacOS X) **gcrypt** required.

**Comment by mikekmv** [comment]
Package dialog needed for vh_gui:
```
# vh_gui
-- ERROR: This script requires dialog to function, please consider installing it or use cli scripts instead (vh).
```

**Comment by Eco-logical** [comment]
added to doc's a while ago forgot to close. If others are found open another issue.
