### ISSUE TITLE
No Downloads Page

### ISSUE THREAD

**Issue by RoLex** [Verlihub/verlihub#75]
_From @KhArtNJava on June 17, 2015 8:57_

http://www.verlihub.net/download

Ops!? Unable to resolve the request "download".
An error occurred when the Web server was processing your request

_Copied from original issue: Verlihub/verlihub-1.0.0#38_

**Comment by RoLex** [comment]
Verlihub download page is main page of the website. Links are pointed to download area here on GitHub.

**Comment by 8la** [comment]
Hey! but... where can i download binary packages for ubuntu? Links on the docs are pointing to http://www.verlihub.net/download and github release have only sources

**Comment by RoLex** [comment]
You have to compile it. You can read how to do that in our wiki or installation text file.
