### ISSUE TITLE
Implementig IPV6 in Verlihub

### ISSUE THREAD

**Issue by carson20** [Verlihub/verlihub#91]
When will verlihub development will  implement ipv6 in unstable version atleast ?

**Comment by RoLex** [comment]
Who knows. How hard is it to implement IPv6? :-) Are we talking about listening sockets only or hub functionality using IPv6 too? User searches and connection requests I mean.

**Comment by carson20** [comment]
well as ipv4 is almost over and  starting development though as you pointing it that it is hard at least we ca start development i beta

**Comment by Mank16** [comment]
The main problem of IPv6 or hybrid socket use is. There is almost none of DC++ clients wich support a IPv6 on a NMDC protocol. From these wich support IPv6 on NMDC and have some larger userbase is only CzDC. All Others popular and publicly aviable client does not support IPv6 on NMDC. Most clients based off DC++ core (DC++ , StrongDC, ApexDC AirDC) does not support IPv6 on NMDC protocol , but "only" on ADC protocol :) . Also i started some work... but can not garatine all is fine...in real word use. see https://github.com/Mank16/verlihub/commits/ipv6 , it is a little outdated by now also :)
