### ISSUE TITLE
Mysql to mariadb by default 

### ISSUE THREAD

**Issue by carson20** [Verlihub/verlihub#92]
When will Mysql will be dropped to replace by  mariadb atleast in development ?

**Comment by RoLex** [comment]
Good question. Did you test Verlihub with MariaDB to 100%? Does everything work? Are you sure that everything works? People are saying that Verlihub runs fine with MariaDB already, both when it comes to compiling and running. Are you having any particular issues?

**Comment by carson20** [comment]
Well everything works in mariadb just wanted to say to include by default mariadb instead of mysql
