### ISSUE TITLE
Startup Script for freeBSD x64 10.3 

### ISSUE THREAD

**Issue by joeshua** [Verlihub/verlihub#93]
Script to start verlihub which could be added 
[Feature request]  modified as default in verlihub in FBSD

[Documentation & help by verlihub team ](https://www.freebsd.org/doc/en/articles/rc-scripting/)

Writing the file in /etc/rc.d

> sudo nano /etc/rc.d/verlihub

```
#!/bin/sh

. /etc/rc.subr

name="vh"
start_cmd="${name}_start"
stop_cmd=":"

vh_start()
{
    echo "Nothing started."
     /usr/local/bin/verlihub --run & disdown
}
```

giving it exec
`chmod +x <file>`

add line in etc.rc.conf
`verlihub_enable="YES"`

**Comment by Eco-logical** [comment]
@mikekmv can you confirm this looks good?  Thanks!

**Comment by joeshua** [comment]
https://github.com/Verlihub/verlihub/issues/93#issuecomment-228583411
Well i do not know the script got helped by mank but wonder how it would work if we using multihub as well at startup if mike could help in this too would be better
