### ISSUE TITLE
Consider moving documentation to a GitHub hosted website

### ISSUE THREAD

**Issue by Eco-logical** [Verlihub/verlihub#94]
# Enhancement Proposal

GitHub Allows Integration with lots of services including [Read the Docs](https://readthedocs.org/).  I propose we use the [GitHub hosted](https://pages.github.com/) website.  The services are free and would be a repository which you can push/pull which would then auto update the hosted pages. GitHub will provide a [free domain](https://help.github.com/articles/what-is-github-pages/) at projectname.github.io or something similar.
## Issues

The current docs in the Wiki while somewhat easy to maintain are kind of a mess as the documentation grows.  While it is easy to update it is not collaborative and the Verlihub community can not propose updates or additions.  It is also kind of a jumbled mess.
## Improvements

Creating documentation in this format would be just as easy to maintain as the current documentation but would be collaborative and easier to write and maintain.
## Alternatives

Lots of documentation frameworks are available for GitHub.  If other alternatives are available or preferred please comment.

**Comment by joeshua** [comment]
Might be alternative (suggestion) as 
[mkdocs](http://www.mkdocs.org/)
or 
[Sphinx](http://www.sphinx-doc.org/en/latest/)

**Comment by Eco-logical** [comment]
Yeah exactly.  Looks as if that one just builds on the others.

mkdocs is built on RTD is built on Sphinx

Seems a bit more customizable with the templates.

Any other Alternatives?
